
path: /workspaces/YOLOV8_seg_synovial_img/yolo_v8 # dataset root dir
train: train/images # train images (relative to 'path') 
val: valid/images # val images (relative to 'path') 

# Classes
names:
  0: vessel